import './globals.css';
import { Inter } from 'next/font/google';
import { AuthProvider } from "@propelauth/nextjs/client";

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Database Doggy',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<AuthProvider authUrl={process.env.NEXT_PUBLIC_AUTH_URL}>
				<body className={inter.className + ' text-regular'}>
					{children}
				</body>
			</AuthProvider>

		</html>
	);
}
